# Generated by Django 4.1.9 on 2023-06-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='isloggedin',
            field=models.BooleanField(default=False),
        ),
    ]
