# Generated by Django 4.0 on 2023-08-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_signup_initials_signup_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_name', models.CharField(max_length=50)),
                ('user2_name', models.CharField(max_length=50)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
    ]
