# Generated by Django 4.0 on 2023-08-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserNames',
        ),
    ]
